/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface MsMenuboardEmbed {
      'auth_key': string;
      'provider': string;
    }
  }

  interface HTMLMsMenuboardEmbedElement extends StencilComponents.MsMenuboardEmbed, HTMLStencilElement {}

  var HTMLMsMenuboardEmbedElement: {
    prototype: HTMLMsMenuboardEmbedElement;
    new (): HTMLMsMenuboardEmbedElement;
  };
  interface HTMLElementTagNameMap {
    'ms-menuboard-embed': HTMLMsMenuboardEmbedElement;
  }
  interface ElementTagNameMap {
    'ms-menuboard-embed': HTMLMsMenuboardEmbedElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'ms-menuboard-embed': JSXElements.MsMenuboardEmbedAttributes;
    }
  }
  namespace JSXElements {
    export interface MsMenuboardEmbedAttributes extends HTMLAttributes {
      'auth_key'?: string;
      'provider'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;